/**:
  ros__parameters:
    look_forward: 0.5
    curv_forward: 0.5
    k_dist: 1.0
    k_ang: 1.0
    k_avel: 1.0
    gain_at_vel: 0.0
    dist_lim: 0.5
    dist_stop: 2.0
    rotate_ang: 0.78539816339
    max_vel: 0.5
    max_angvel: 1.0
    max_acc: 1.0
    max_angacc: 2.0
    acc_toc_factor: 0.9
    angacc_toc_factor: 0.9
    path_step: 1
    goal_tolerance_dist: 0.2
    goal_tolerance_ang: 0.1
    stop_tolerance_dist: 0.1
    stop_tolerance_ang: 0.05
    no_position_control_dist: 0.0
    min_tracking_path: 0.0
    allow_backward: True
    limit_vel_by_avel: False
    check_old_path: False
    epsilon: 0.001
    use_time_optimal_control: True
    time_optimal_control_future_gain: 1.5
    k_ang_rotation: 1.0
    k_avel_rotation: 1.0
    goal_tolerance_lin_vel: 0.0
    goal_tolerance_ang_vel: 0.0
